"""
Klasa TextComparison reprezentuje porównanie dwóch tekstów
- tekstu wejściowego i tekstu wygenerowanego przez model.
"""

from dataclasses import dataclass


@dataclass
class TextComparison:
    # Text which was first as input
    input_text: str
    # Text which was generated by model
    output_text: str

    def __post_init__(self):
        """Initialize the class"""
